# Generated by Django 5.0 on 2025-08-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_points', models.IntegerField()),
                ('wins_Oncurrent_round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Winorloss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=512)),
                ('win', models.CharField(max_length=100)),
            ],
        ),
    ]
